//DATA-MATH

var participantCount = 45;
var passCount = 16;

//arrays starts from 1 (index 0 ignored)

var data_name1 = [
"", //ignored
"Adam Omar Munandar",
"Adelia Putri",
"Akira Mushima",
"Aldeo Malta",
"Alex Sander",
"Alexio Nolan Nugroho",
"Andree Fransiscus Masalle",
"Andrew Daniel Janong",
"Angeline Valencia",
"Bryan Wijaya",
"Christopher Pranta A",
"Clarrisa Tania Tunggal",
"Cynthia Nathanaline",
"Darren Darwis T",
"Diandra Najmi Kirana",
"Elbert Benedict",
"Eugenie Alana Florencia",
"Eveline Iskandar",
"Fakhri Muhammad Mahenda",
"Farrel D.",
"Fernando Nathaniel Sutanto",
"Fifinellametta Kurniadi",
"Ignatius John H. Chan",
"Jason Chow",
"Jevon Naldo Yoshield",
"Kandida Edgina Gunawan",
"Kenneth Vincenzo Salim",
"Khalisa Hana Aida Putri",
"M Nadhif H",
"M. Nabil Zuhair",
"Mariano Gerardus Senduk",
"Marion Alberta Santoso",
"Mas Eufrat Piustan",
"Michelle A Kwan",
"Muhammad Ali Z.",
"Nabil Ibdrurrahman",
"Oliverio Theophilus",
"Sandy Kristian W",
"Shielda Kamilia H",
"Steven Nathanael M",
"Timotius Andersen",
"Vannes Wijaya",
"Vaughn Daniel K Siburian",
"Vindasya Almelra",
"Yesaya A B Napitupulu"
];


var data_name2 = [
"", //ignored
"Reyfandi Nawal Pratama",
"Nasywa Hanan Huriyah",
"Muhammad Arief Wibisono",
"Lunar Sebastian",
"Joceline Tay",
"Wilson Widyadhana",
"Toar Daniel Lapian",
"Kevin Jonathan Kusnomo",
"Vincent Ferdinand Kwee",
"Jonathan Patrick B",
"Madeline Yensia A",
"Kenji Gunawan",
"Gabriella Galuh Cornelia P",
"Dylan Christopher Permadi",
"Ariana Dwi Listyawaty",
"Rafael Kristoforus",
"Nicholas Christian",
"I Gusti Ayu Indira L. A.",
"Ahmad Syarif Hidayat",
"Daffa A.",
"Edgar Sulaeman",
"Tharreo Geronimo Baryosh",
"Verine",
"Kenz Antonio",
"Felix",
"Benediktus Gianto Jarod",
"Stanley Kurniawan",
"Madia Ardini Daniella T",
"Reynaldi",
"Khaliza Marzania",
"Toar Calvin Tamboto",
"William Raffa Dharmawan",
"Yohanes Ari Putra Pandipotan",
"Beatrice Abdinegara",
"Deandra V.",
"Wage Mareto",
"Bryan Florentino",
"Fiona Valentin",
"Raisa Rahmadiesa Z",
"Sydney Tjandra",
"Phoebe Pascaline B",
"Clement Jason",
"Alfin Sanders",
"Fauzan Ibrahim Zakaria",
"Christian Amriel Susanto"
];


var data_school = [
"", //ignored
"SMPN 115 Jakarta",
"SMP IT Nurul Fikri",
"SMP Al Azhar 8 Kemang",
"SMP Global Prestasi Bekasi",
"SMP Yos Sudarso Batam",
"SMPK 8 Penabur",
"SMP Lokon St. Nikolaus Tomohon",
"SMPK 4 Penabur",
"SMP Yos Sudarso Batam",
"SMP Regina Pacis",
"SMPK 5 Penabur",
"SMPK Penabur Kota Wisata",
"SMP Yos Sudarso Batam",
"SMPK 4 Penabur",
"SMPN 115 Jakarta",
"SMPK Penabur Gading Serpong",
"SMPK Penabur Holis",
"SMP Yos Sudarso Batam",
"SMP IT Insan Harapan",
"SMP Kharisma Bangsa",
"SMP Santa Maria Cirebon",
"SMP Darma Yudha Pekanbaru",
"SMP Yos Sudarso Batam",
"SMP Darma Yudha Pekanbaru",
"SMP Katholik Santu Petrus Pontianak",
"SMP Katholik Rajawali Makassar",
"BINUS School Serpong",
"SMPN 115 Jakarta",
"SMP Labschool Jakarta",
"SMPN 115 Jakarta",
"SMP Lokon St. Nikolaus Tomohon",
"SMPK Penabur Kota Jababeka",
"SMP Katholik Santu Petrus Pontianak",
"SMP IPEKA Balikpapan",
"SMP Kharisma Bangsa",
"SMPN 115 Jakarta",
"SMPK Penabur Gading Serpong",
"SMPK Penabur Cirebon",
"SMPN 1 Bogor",
"SMP Santa Laurensia",
"SMP Santa Laurensia",
"SMP Darma Yudha Pekanbaru",
"SMP Lokon St. Nikolaus Tomohon",
"SMPN 2 Depok",
"SMPK Nasional Plus Penabur Sentul City"
];


var kode_pst = [
"", //ignored
"M - 01",
"M - 02",
"M - 03",
"M - 04",
"M - 05",
"M - 06",
"M - 07",
"M - 08",
"M - 09",
"M - 10",
"M - 11",
"M - 12",
"M - 13",
"M - 14",
"M - 15",
"M - 16",
"M - 17",
"M - 18",
"M - 19",
"M - 20",
"M - 21",
"M - 22",
"M - 23",
"M - 24",
"M - 25",
"M - 26",
"M - 27",
"M - 28",
"M - 29",
"M - 30",
"M - 31",
"M - 32",
"M - 33",
"M - 34",
"M - 35",
"M - 36",
"M - 37",
"M - 38",
"M - 39",
"M - 40",
"M - 41",
"M - 42",
"M - 43",
"M - 44",
"M - 45"
];

//rank/no of passing participants

var data_rank = 
