//DATA-SCIENCE

var participantCount = 35;
var passCount = 3;

//arrays starts from 1 (index 0 ignored)
// nama paling panjang 30 karakter !!!!!!
var data_name1 = [
"", //ignored
"Aditia Fortuna",
"Alexander",
"Alicia Cherie C.",
"Anthony Bryant",
"Ariela Portia Tunggaldinata",
"Aulia Sharely Mustika H.",
"Benedict Gabriel Liang",
"Christopher Ivan Budiwardhana",
"Delvin Wijaya",
"Ellena Vianne",
"Evan Samuel Bona Parulian S.",
"Fachri Aziz",
"Fakhrin Syouqiy Fauzan",
"Farrel N.",
"Gabriela E. W.",
"Gwyneth H.K. Tambatjong",
"Hanaan Nida Santosa",
"Janice Geraldin Chen",
"Karen Anne Mary",
"Luthfi Adi Nugraha",
"Maria Flora Renata",
"Matthew Alexander Keng",
"Nicholas Setia Atmaja",
"Nicolas Garrie",
"Noel Christoffel Simbolon",
"Novea Indratmo",
"Rayhan Nugraha Putra",
"Samuel Yudhistira",
"Savana Nazwa",
"So Ran",
"Stanislaus Clifton Wangsadinata",
"Stefani Angel Gosali, GO",
"Steven Jones",
"Valentino Vinent Risrianto",
"Wilbert Neil T."
];

var data_name2 = [
"", //ignored
"Ranti Aisha Putri",
"M. Zulfan R.",
"Vincent E.",
"Mikhael Laurensius H",
"Melvin Kent Jonathan",
"Ghania Parshanifa Koembo",
"Aurelia Gabrielle Saputra",
"Leticia Seraphine Nathanael",
"John Howard Wijaya",
"Mario Alvaro",
"Joan Carol Louisa Sihombing",
"Hizounya Maycinto Alkian",
"Caleb Faith Adnaka",
"Vania Andaru",
"",
"Injilia E.J. Rumagit",
"Aliya Lathifa Putri",
"Pascalis Pandey",
"Margie Lynetta Gunawan",
"M. Ghazali Amran",
"Yehezkiel Obed Edom",
"Harris Ramsi Gunawan",
"Patricia Avril",
"Aiko Mary Wong",
"Seren Elizabeth Siahaan",
"Claire Emmanuela Selamat",
"Nathaniel Amsal Hiro",
"Jonathan Setiawan",
"Jasmine Lianna",
"I Made Raegana M.",
"M. Fairuz Azfa Elsubeza",
"Stevan Gerard Gunawan",
"Edward Humianto",
"Vincentius Roger Kuswara",
"Petra Michael"
];

var data_school = [
"", //ignored
"SMP Al Azhar 8 Kemang",
"SMPK Global Prestasi",
"SMPK Penabur GS",
"SMPK Penabur Tirtamarta",
"SMPK 4 Penabur",
"SMPN 115 Jakarta",
"SMP Santa Laurensia",
"SMPK Penabur GS",
"SMP Darma Yudha",
"SMPK 4 Penabur",
"SMPK Penabur Tirtamarta",
"SMPN 115 Jakarta",
"SMP Labschool Kebayoran",
"SMPN 115 Jakarta",
"SMPK Penabur GS",
"SMP Lokon St. Nikolaus Tomohon",
"SMPN 115 Jakarta",
"SMP Santa Laurensia",
"SMP Santa Maria Cirebon",
"SMP Al Azhar 8 Kemang",
"SMPK Penabur Jababeka",
"SMPK 4 Penabur",
"SMPK Penabur Tirtamarta",
"SMP Santa Laurensia",
"SMPK Penabur Kota Wisata",
"SMP Santa Laurensia",
"SMPN 115 Jakarta",
"SMP Santa Laurensia",
"SMP Kharisma Bangsa",
"SMPK Global Prestasi",
"SMP Darma Yudha",
"SMP Katholik Rajawali Makassar",
"SMPK 6 Penabur",
"SMPK Kalam Kudus Solo",
"SMPK Penabur Holis"
];

var kode_pst = [
"", //ignored
"S - 01",
"S - 02",
"S - 03",
"S - 04",
"S - 05",
"S - 06",
"S - 07",
"S - 08",
"S - 09",
"S - 10",
"S - 11",
"S - 12",
"S - 13",
"S - 14",
"S - 15",
"S - 16",
"S - 17",
"S - 18",
"S - 19",
"S - 20",
"S - 21",
"S - 22",
"S - 23",
"S - 24",
"S - 25",
"S - 26",
"S - 27",
"S - 28",
"S - 29",
"S - 30",
"S - 31",
"S - 32",
"S - 33",
"S - 34",
"S - 35"
];

//rank/no of passing participants

var data_rank = 
